doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '5.7'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            App\Shop\Cart\Domain\Model:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/cart'
                prefix: 'App\Shop\Cart\Domain\Model'
            App\Shop\Catalogue\Domain\Model:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/catalogue'
                prefix: 'App\Shop\Catalogue\Domain\Model'
            App\Shop\Common\Price:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/vo'
                prefix: 'App\Shop\Common\Price'
            App\Shop\Common\Event:
                is_bundle: false
                type: xml
                dir: '%kernel.project_dir%/config/doctrine/event'
                prefix: 'App\Shop\Common\Event'
#            App\Shop\Cart\Domain\Event:
#                is_bundle: false
#                type: xml
#                dir: '%kernel.project_dir%/config/doctrine/event'
#                prefix: 'App\Shop\Cart\Domain\Event'
#            App\Shop\Catalogue\Domain\Event:
#                is_bundle: false
#                type: xml
#                dir: '%kernel.project_dir%/config/doctrine/event'
#                prefix: 'App\Shop\Catalogue\Domain\Event'
